# Generated by Django 4.2.16 on 2024-10-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_user_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='title',
            new_name='discussion_title',
        ),
    ]
