# Generated by Django 4.2.16 on 2024-10-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_title_discussion_discussion_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='discussion',
            new_name='discussion_forum',
        ),
    ]
