# Generated by Django 4.2.16 on 2024-10-05 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_discussion_discussion_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion_forum',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.discussion_forum'),
        ),
    ]
