# Generated by Django 4.2.16 on 2024-10-05 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion_forum',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='myapp.category'),
            preserve_default=False,
        ),
    ]
