# Generated by Django 4.2.16 on 2024-10-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_discussion_forum_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion_forum',
            name='category',
        ),
    ]
