# Generated by Django 4.2.16 on 2024-10-06 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_discussion_forum_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('obj_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('obj_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('q_question', models.CharField(max_length=255)),
                ('q_answer', models.CharField(max_length=100)),
                ('option_1', models.CharField(default='Default option', max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('obj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.object')),
            ],
        ),
    ]
